# Generated by Django 2.2.7 on 2019-11-09 09:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20191109_1103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('78950012-8f7a-48f7-93da-23dab3ddb79f'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
